updated main to use singularity

diff --git a/main b/main
--- a/main
+++ b/main
@@ -35,9 +35,7 @@ else
 	cp $moving ./;
 	cp $static ./;
 fi
-echo "Finished copying tractograms"
 
-# Tractogram Input converter
 echo "Tractogram conversion to trk"
 if [ -f $mov_life_id'_track.tck' -a $stat_life_id'_track.tck' ];then
 	echo "Input in tck format. Convert it to trk."
@@ -48,10 +46,11 @@ if [ -f $mov_life_id'_track.tck' -a $stat_life_id'_track.tck' ];then
     singularity exec docker://brainlife/dipy:0.14 "python ./tck2trk.py $mov_t1 ${mov_life_id}_track.tck && python ./tck2trk.py $stat_t1 ${stat_life_id}_track.tck"
 else
 	echo "Input in fe format. Convert it to trk."
-	matlab -nosplash -nodisplay -r lifeConverter
+	#matlab -nosplash -nodisplay -r lifeConverter
+    singularity exec docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/lifeConverter
+
 	mv life_moving_output.trk $mov_life_id'_track.trk';
 	mv life_static_output.trk $stat_life_id'_track.trk';
-
 	ret=$?
 	if [ ! $ret -eq 0 ]; then
 		echo "Tractogram conversion failed"
@@ -60,9 +59,9 @@ else
 	fi
 fi
 
-# AFQ conversion
-matlab -nosplach -nodisplay -r "afqConverter1()"
 echo "AFQ conversion to trk"
+#matlab -nosplach -nodisplay -r "afqConverter1()"
+singularity exec docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/afqConverter1
 ret=$?
 	if [ ! $ret -eq 0 ]; then
 		echo "AFQ conversion failed"
@@ -70,9 +69,9 @@ ret=$?
 		exit $ret
 	fi
 
-# Compute affine transformation with SLR
 echo "Compute affine with SLR"
 #python tractograms_slr.py -moving $mov_life_id'_track.trk' -static $stat_life_id'_track.trk' 
+singularity exec docker://brainlife/dipy:0.14 "python ./tractograms_slr.py -moving ${mov_life_id}_track.trk -static ${stat_life_id}_track.trk"
 ret=$?
 	if [ ! $ret -eq 0 ]; then
 		echo "Alignment failed"
@@ -80,9 +79,9 @@ ret=$?
 		exit $ret
 	fi
 
-# Compute dissimilarity of target tractogram
 echo "Compute dissimilarity of target tractogram"
-python compute_kdtree_and_dr_tractogram.py -static $stat_life_id'_track.trk' 
+#python compute_kdtree_and_dr_tractogram.py -static $stat_life_id'_track.trk' 
+singularity exec docker://brainlife/dipy:0.14 "python ./compute_kdtree_and_dr_tractogram.py -static ${stat_life_id}_track.trk"
 ret=$?
 	if [ ! $ret -eq 0 ]; then
 		echo "Alignment failed"
@@ -90,69 +89,61 @@ ret=$?
 		exit $ret
 	fi
 
-# Run LAP single example
 echo "Running LAP single example"
 mkdir tracts_tck;
-
 while read tract_name; do         
-
     echo "Tract name: $tract_name"; 
-
     tract_example=$tract_name'_tract.trk'; 
     output_filename=${subjID}'_'$tract_name'_tract_E'$mov_afq_id'.tck';
     array_filename='result_lap';
     superset_filename='superset_idx';
-    python single_lap.py -moving $mov_life_id'_track.trk' -static $stat_life_id'_track.trk' -ex $tract_example -out $output_filename;
+    #python single_lap.py -moving $mov_life_id'_track.trk' -static $stat_life_id'_track.trk' -ex $tract_example -out $output_filename;
+    singularity exec docker://brainlife/dipy:0.14 "python ./single_lap.py -moving ${mov_life_id}_track.trk -static ${stat_life_id}_track.trk -ex $tract_example -out $output_filename"
+    ret=$?
+    if [ ! $ret -eq 0 ]; then
+        echo "LAP single example failed"
+        echo $ret > finished
+        exit $ret
+    fi
+
     mv $output_filename tracts_tck;
     mv result_lap.npy ${subjID}'_'${tract_name}'_'$array_filename'_E'$mov_afq_id'.npy';
     mv superset_idx.npy ${subjID}'_'${tract_name}'_'$superset_filename'_E'$mov_afq_id'.npy';
-
 done < tract_name_list.txt
 
-ret=$?
-if [ ! $ret -eq 0 ]; then
-	echo "LAP single example failed"
-	echo $ret > finished
-	exit $ret
-fi
-
-# Build partial tractogram
+echo "Build partial tractogram"
 output_filename=${subjID}'_var-partial_tract_'E${mov_afq_id}'.tck';
-python build_partial_tractogram.py -tracts_tck_dir 'tracts_tck' -out ${output_filename};
-
+#python build_partial_tractogram.py -tracts_tck_dir 'tracts_tck' -out ${output_filename};
+singularity exec docker://brainlife/dipy:0.14 "python ./build_partial_tractogram.py -tracts_tck_dir tracts_tck -out $output_filename"
 if [ -f ${output_filename} ]; then 
-    	echo "Partial tractogram built."
+    echo "Partial tractogram built."
 else 
 	echo "Partial tractogram missing."
 	exit 1
 fi
 
-# Build a fg structure from tck registered
+echo "Build a fg structure from tck registered"
 while read tract_name; do         
-
     echo "Tract name: $tract_name"; 
-
     tck_filename=\'tracts_tck/${subjID}_${tract_name}_tract_E${mov_afq_id}.tck\';
     tract_filename=\'$tract_name\';
     echo $tck_filename;
     echo $tract_filename;
-    matlab -nosplash -nodisplay -r "my_convert_tck2fg($tck_filename, $tract_filename)";
-
-    if [ -f $tract_name'.mat' ]; then 
+    #matlab -nosplash -nodisplay -r "my_convert_tck2fg($tck_filename, $tract_filename)";
+    singularity exec docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/my_convert_tck2fg $tck_filename $tract_filename"
+    if [ -f ${tract_name}.mat ]; then 
     	echo "tck2fg conversion done."
     else 
-	echo "tck2fg conversion failed."
-	exit 1
+        echo "tck2fg conversion failed."
+        exit 1
     fi
-    
 done < tract_name_list.txt
 
-# Merge the fg structures and create the files for the wmc structure
-echo "Creating the WMC structure"
-matlab -nosplash -nodisplay -r "my_fg_merge()";
-
+echo "Merge the fg structures and create the files for the wmc structure"
+#matlab -nosplash -nodisplay -r "my_fg_merge()"
+singularity exec docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/my_fg_merge
 if [ -f 'output.mat' ]; then 
-    	echo "WCM structure created."
+    echo "WCM structure created."
 else 
 	echo "WCM structure missing."
 	exit 1
