added 3 optiona tracts

diff --git a/main b/main
--- a/main
+++ b/main
@@ -68,24 +68,26 @@ fi
 
 # Run LAP single example
 echo "Running LAP single example"
-if [ -f "tract.trk" ];then
-	echo "File exists. Complete"
-else
-	tract_name='./*tract.trk'
-	base_name=$(basename $tract_name .trk)
-	output_filename=${subjID}'_'$base_name'_E'$mov_afq_id'.tck'
-	array_filename='result_lap'
-	superset_filename='superset_idx'
-	python lap_single_example.py -moving life_moving_output.trk -static life_static_output.trk -ex $tract_name -out $output_filename;
-	mv result_lap.npy ${subjID}'_'${base_name/tract/$array_filename}'_E'$mov_afq_id'.npy'
-	mv superset_idx.npy ${subjID}'_'${base_name/tract/$superset_filename}'_E'$mov_afq_id'.npy'
 
-	ret=$?
-	if [ ! $ret -eq 0 ]; then
-		echo "LAP single example failed"
-		echo $ret > finished
-		exit $ret
-	fi
+while read tract_name; do         
+
+    echo "Tract name: $tract_name"; 
+
+    tract_example=$tract_name'_tract.trk' 
+    output_filename=${subjID}'_'$tract_name'_E'$mov_afq_id'.tck'
+    array_filename='result_lap'
+    superset_filename='superset_idx'
+    python lap_single_example.py -moving life_moving_output.trk -static life_static_output.trk -ex $tract_example -out $output_filename;
+    mv result_lap.npy ${subjID}'_'${tract_name}'_'$array_filename'_E'$mov_afq_id'.npy'
+    mv superset_idx.npy ${subjID}'_'${tract_name}'_'$superset_filename'_E'$mov_afq_id'.npy'
+
+done < tract_name_list.txt
+
+ret=$?
+if [ ! $ret -eq 0 ]; then
+	echo "LAP single example failed"
+	echo $ret > finished
+	exit $ret
 fi
 
 echo "Complete"
