split lap_single_example.py into three scripts

diff --git a/main b/main
--- a/main
+++ b/main
@@ -90,6 +90,26 @@ ret=$?
 		exit $ret
 	fi
 
+# Compute affine transformation with SLR
+echo "Compute affine with SLR"
+python tractograms_slr.py -moving $mov_life_id'_track.trk' -static $stat_life_id'_track.trk' 
+ret=$?
+	if [ ! $ret -eq 0 ]; then
+		echo "Alignment failed"
+		echo $ret > finished
+		exit $ret
+	fi
+
+# Compute dissimilarity of target tractogram
+echo "Compute dissimilarity of target tractogram"
+python compute_kdt_and_dr_tractogram.py -static $stat_life_id'_track.trk' 
+ret=$?
+	if [ ! $ret -eq 0 ]; then
+		echo "Alignment failed"
+		echo $ret > finished
+		exit $ret
+	fi
+
 # Run LAP single example
 echo "Running LAP single example"
 mkdir tracts_tck;
@@ -102,7 +122,7 @@ while read tract_name; do
     output_filename=${subjID}'_'$tract_name'_tract_E'$mov_afq_id'.tck';
     array_filename='result_lap';
     superset_filename='superset_idx';
-    python lap_single_example.py -moving $mov_life_id'_track.trk' -static $stat_life_id'_track.trk' -ex $tract_example -out $output_filename;
+    python single_lap.py -moving $mov_life_id'_track.trk' -static $stat_life_id'_track.trk' -ex $tract_example -out $output_filename;
     mv $output_filename tracts_tck;
     mv result_lap.npy ${subjID}'_'${tract_name}'_'$array_filename'_E'$mov_afq_id'.npy';
     mv superset_idx.npy ${subjID}'_'${tract_name}'_'$superset_filename'_E'$mov_afq_id'.npy';
@@ -116,6 +136,16 @@ if [ ! $ret -eq 0 ]; then
 	exit $ret
 fi
 
+# Build partial tractogram
+output_filename=${subjID}'_var-partial_tract_'E${mov_afq_id}'.tck';
+python build_partial_tractogram.py -tracts_tck_dir 'tracts_tck' -out ${output_filename};
+
+if [ -f ${output_filename} ]; then 
+    	echo "Partial tractogram built."
+else 
+	echo "Partial tractogram missing."
+	exit 1
+fi
 
 # Build a fg structure from tck registered
 while read tract_name; do         
@@ -137,11 +167,8 @@ while read tract_name; do
     
 done < tract_name_list.txt
 
-
 # Merge the fg structures and create the files for the wmc structure
 echo "Creating the WMC structure"
-output_filename=${subjID}'_var-partial_tract_'E${mov_afq_id}'.tck';
-python build_partial_tractogram.py -tracts_tck_dir 'tracts_tck' -out ${output_filename};
 matlab -nosplash -nodisplay -r "my_fg_merge()";
 
 if [ -f 'output.mat' ]; then 
